name: ci

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-major: 2.7
            ruby-version: 2.7.1

          - ruby-major: 2.7
            ruby-version: 2.7.2

          - ruby-major: 3.0
            ruby-version: 3.0.2

          - ruby-major: 3.0
            ruby-version: 3.0.4

          - ruby-major: 3.1
            ruby-version: 3.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: docker
          file: ruby.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.ruby-version }}
